# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [21]:
import numpy as np
from numpy.random import randint as ri

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [22]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", np.power(mat1,3))
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.sqrt(mat1))


1st Matrix of random single-digit numbers
----------------------------------------
 [[6 1 9]
 [4 7 5]
 [9 8 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 5 4]
 [9 8 5]
 [6 3 2]]

Addition
------------------
 [[11  6 13]
 [13 15 10]
 [15 11  7]]

Multiplication
------------------
 [[30  5 36]
 [36 56 25]
 [54 24 10]]

Division
------------------
 [[1.2        0.2        2.25      ]
 [0.44444444 0.875      1.        ]
 [1.5        2.66666667 2.5       ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[ 8 -7 19]
 [-6  5  5]
 [15 18 11]]

Addition of a scalar (100)
-------------------------
 [[106 101 109]
 [104 107 105]
 [109 108 105]]

Exponentiation, matrix cubed here
----------------------------------------
 [[216   1 729]
 [ 64 343 125]
 [729 512 125]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[2.44948974 1.         3.        ]
 [2.         2.64575131 2.23606798]
 [3.  

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [31]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=0))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat1,axis=1))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(ri(1,99,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 8 1]
 [2 9 6]
 [2 3 4]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[2 3 4]
 [9 6 7]
 [2 9 9]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 36

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [10 17  9]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 5 20 11]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [  4 216  24]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [  8 108  24]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.0

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.8284271247461

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [20]:
##Solution
mat1 = np.array(ri(1,10,9)).reshape(3,3)
print("Created 3X3 matrix\n","-"*20,"\n",mat1)
print("Modifying the shape to 9*1\n","-"*30,"\n",mat1.reshape(9,1))


Created 3X3 matrix
 -------------------- 
 [[1 2 8]
 [8 5 1]
 [9 9 7]]
Modifying the shape to 9*1
 ------------------------------ 
 [[1]
 [2]
 [8]
 [8]
 [5]
 [1]
 [9]
 [9]
 [7]]


### 4.Sort

In [33]:

A = np.array(ri(1,100,size=10))
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [66 50 30 94 77 35 93 72 26 85]

Here is the sorted vector
 -------------------------------------------------- 
 [26 30 35 50 66 72 77 85 93 94]


In [38]:
#M = ****** #  5*5 Matrix of random interegrs
M= np.array(ri(1,100,25)).reshape(5,5)
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[84 68 87 28 83]
 [11 80 96 91 75]
 [94 86 70 61 14]
 [90 52 19 48 89]
 [56 43 65 29 27]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[28 68 83 84 87]
 [11 75 80 91 96]
 [14 61 70 86 94]
 [19 48 52 89 90]
 [27 29 43 56 65]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[11 43 19 28 14]
 [56 52 65 29 27]
 [84 68 70 48 75]
 [90 80 87 61 83]
 [94 86 96 91 89]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [41]:
# Fill the following ***** with appropriate solution.
a= np.array(ri(1,100,size=10))
b= np.array(ri(1,100,size=10))
c= np.array(ri(1,100,size=10))

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.amax(a))
print("Max of b:", np.amax(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Max of a:", np.amax(a))
print("Max of b:", np.amax(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))



a: [60 70 50 65 22 99 33 98 30 67]
b: [79 65 55 41 65 89 72 70 10 98]
c: [24 65 96  2 44 11 57 29 15  3]
Max of a: 99
Max of b: 98
Max of a location: 5
Max of b location: 9
Max of c location: 2
Max of a: 99
Max of b: 98
Max of a location: 5
Max of b location: 9
Max of c location: 2


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [42]:

mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n", mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n", mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[8 5 4]
 [7 8 2]
 [8 2 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 6 2]
 [8 5 6]
 [2 4 6]]

Sq-root of 1st matrix using np
------------------
 [[2.82842712 2.23606798 2.        ]
 [2.64575131 2.82842712 1.41421356]
 [2.82842712 1.41421356 2.        ]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[2980.95798704  148.4131591    54.59815003]
 [1096.63315843 2980.95798704    7.3890561 ]
 [2980.95798704    7.3890561    54.59815003]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.90308999 0.69897    0.60205999]
 [0.84509804 0.90308999 0.30103   ]
 [0.90308999 0.30103    0.60205999]]

Modulo reminder using np
 -------------------------------------------------- 
 [[2 5 0]
 [7 3 2]
 [0 2 4]]


### 7.Generating matrices from distributions

In [43]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.60667966 0.75554865 0.49647574]
 [0.54123289 0.61494061 0.99153251]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.03303514  0.55028953 -1.19427204]
 [ 0.00779352 -0.64197463 -0.31787446]
 [-1.4158902   1.2636877  -0.37492685]
 [ 0.53423576 -0.61739982 -0.00610766]]
Random integer vector: [84 80 14 32 87 79 49 65 14 54]

Random integer matrix
[[ 6 47  1 62]
 [ 2 32 21 61]
 [65 87 71 81]
 [62 70 98 19]]

20 samples drawn from a dice throw: [5 6 3 2 6 1 3 6 5 4 2 5 2 3 6 4 4 4 1 5]


### 8.Find the nearest value from a given number in an array using NumPy.

In [51]:
#Steps
#Create an array of 5 random element from 1 to 12
arr = np.random.uniform(1, 12, 5)
print('Array elements are: ', arr)
#Suppose find the nearest values of 10 in an array so set value=10
value = 10
#find the index where difference is minimum and get the element
n = arr.flat[np.abs(arr - value).argmin()]
print("Nearest value is : ",n)



Array elements are:  [6.96403055 7.1164754  5.12113184 1.70891003 9.63929111]
Nearest value is :  9.639291105198776


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [87]:
import numpy as np
x = np.arange(3)
l =[-1,0,1]
np.row_stack([x+(i*x) for i in l])

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])